crm/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path

app_name = 'crm'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('collector_list', views.collector_list, name='collector_list'),
    path('collector/<int:pk>/edit/', views.collector_edit, name='collector_edit'),
    path('collector/<int:pk>/delete/', views.collector_delete, name='collector_delete'),
    path('console_list', views.console_list, name='console_list'),
    path('console/create/', views.console_new, name='console_new'),
    path('console/<int:pk>/edit/', views.console_edit, name='console_edit'),
    path('console/<int:pk>/delete/', views.console_delete, name='console_delete'),
    path('videogame_list', views.videogame_list, name='videogame_list'),
    path('videogame/create/', views.videogame_new, name='videogame_new'),
    path('videogame/<int:pk>/edit/', views.videogame_edit, name='videogame_edit'),
    path('videogame/<int:pk>/delete/', views.videogame_delete, name='videogame_delete'),
    path('collector/<int:pk>/summary/', views.summary, name='summary'),
]

gamecollection/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

crm/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Collector(models.Model):
    coll_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    address = models.CharField(max_length=200)
    account_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.coll_name)


class Console(models.Model):
    coll_name = models.ForeignKey(Collector, on_delete=models.CASCADE, related_name='consoles')
    console_name = models.CharField(max_length=100)
    description = models.TextField()
    console_model = models.CharField(max_length=100)
    console_color = models.CharField(max_length=100)
    console_brand = models.CharField(max_length=100)
    console_price = models.DecimalField(max_digits=10, decimal_places=2)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.coll_name)


class VideoGame(models.Model):
    coll_name = models.ForeignKey(Collector, on_delete=models.CASCADE, related_name='videogames')
    videogame_name = models.CharField(max_length=100)
    videogame_console = models.CharField(max_length=100)
    v_description = models.TextField()
    quantity = models.IntegerField()
    videogame_charge = models.DecimalField(max_digits=10, decimal_places=2)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.coll_name)

crm/forms.py
from django import forms
from .models import Collector, Console, VideoGame


class CollectorForm(forms.ModelForm):
    class Meta:
        model = Collector
        fields = ('coll_name', 'account_number', 'address', 'city', 'state', 'zipcode', 'email','phone_number')


class ConsoleForm(forms.ModelForm):
   class Meta:
        model = Console
        fields = ('coll_name', 'console_name', 'description', 'console_model', 'console_color', 'console_brand', 'console_price' )


class VideoGameForm(forms.ModelForm):
    class Meta:
        model = VideoGame
        fields = ('coll_name', 'videogame_name', 'videogame_console', 'v_description', 'quantity', 'videogame_charge' )

crm/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.db.models import Sum

now = timezone.now()


def home(request):
    return render(request, 'crm/home.html',
                  {'crm': home})


@login_required
def collector_list(request):
    collector = Collector.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/collector_list.html',
                  {'collectors': collector})


@login_required
def collector_edit(request, pk):
    collector = get_object_or_404(Collector, pk=pk)
    if request.method == "POST":
        # update
        form = CollectorForm(request.POST, instance=collector)
        if form.is_valid():
            collector = form.save(commit=False)
            collector.updated_date = timezone.now()
            collector.save()
            collector = Collector.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/collector_list.html',
                          {'collectors': collector})
    else:
        # edit
        form = CollectorForm(instance=collector)
    return render(request, 'crm/collector_edit.html', {'form': form})


@login_required
def collector_delete(request, pk):
    collector = get_object_or_404(Collector, pk=pk)
    collector.delete()
    return redirect('crm:collector_list')


@login_required
def console_list(request):
    consoles = Console.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/console_list.html', {'consoles': consoles})


@login_required
def console_new(request):
    if request.method == "POST":
        form = ConsoleForm(request.POST)
        if form.is_valid():
            console = form.save(commit=False)
            console.created_date = timezone.now()
            console.save()
            consoles = Console.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/console_list.html',
                          {'consoles': consoles})
    else:
        form = ConsoleForm()
        # print("Else")
    return render(request, 'crm/console_new.html', {'form': form})


@login_required
def console_edit(request, pk):
    console = get_object_or_404(Console, pk=pk)
    if request.method == "POST":
        form = ConsoleForm(request.POST, instance=console)
        if form.is_valid():
            console = form.save()
            # console.collector = console.id
            console.updated_date = timezone.now()
            console.save()
            consoles = Console.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/console_list.html', {'consoles': consoles})
    else:
        # print("else")
        form = ConsoleForm(instance=console)
    return render(request, 'crm/console_edit.html', {'form': form})


@login_required
def console_delete(request, pk):
    console = get_object_or_404(Console, pk=pk)
    console.delete()
    return redirect('crm:console_list')


@login_required
def videogame_list(request):
    videogames = VideoGame.objects.filter(created_date__lte=timezone.now())
    return render(request, 'crm/videogame_list.html', {'videogames': videogames})


@login_required
def videogame_new(request):
    if request.method == "POST":
        form = VideoGameForm(request.POST)
        if form.is_valid():
            videogame = form.save(commit=False)
            videogame.created_date = timezone.now()
            videogame.save()
            videogames = VideoGame.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/videogame_list.html',
                          {'videogames': videogames})
    else:
        form = VideoGameForm()
        # print("Else")
    return render(request, 'crm/videogame_new.html', {'form': form})


@login_required
def videogame_edit(request, pk):
    console = get_object_or_404(VideoGame, pk=pk)
    if request.method == "POST":
        form = VideoGameForm(request.POST, instance=console)
        if form.is_valid():
            videogame = form.save()
            # videogame.collector = videogame.id
            videogame.updated_date = timezone.now()
            videogame.save()
            videogames = VideoGame.objects.filter(created_date__lte=timezone.now())
            return render(request, 'crm/videogame_list.html', {'videogames': videogames})
    else:
        # print("else")
        form = VideoGameForm(instance=console)
    return render(request, 'crm/videogame_edit.html', {'form': form})


@login_required
def videogame_delete(request, pk):
    videogame = get_object_or_404(VideoGame, pk=pk)
    videogame.delete()
    return redirect('crm:videogame_list')


@login_required
def summary(request, pk):
    collector = get_object_or_404(Collector, pk=pk)
    collectors = Collector.objects.filter(created_date__lte=timezone.now())
    consoles = Console.objects.filter(coll_name=pk)
    videogames = VideoGame.objects.filter(coll_name=pk)
    sum_console_charge = Console.objects.filter(coll_name=pk).aggregate(Sum('console_price'))
    sum_videogame_charge = VideoGame.objects.filter(coll_name=pk).aggregate(Sum('videogame_charge'))
    return render(request, 'crm/summary.html', {'collectors': collectors,
                                                'videogames': videogames,
                                                'consoles': consoles,
                                                'sum_console_charge': sum_console_charge,
                                                'sum_videogame_charge': sum_videogame_charge, })

crm/templates/crm/base.html
{% load static %}

<html lang="en">
<head>
    <title>GameCollection</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                GameCollection
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'crm:home' %}">Home</a></li>
                <li><a href="{% url 'crm:collector_list' %}">Collectors</a></li>
               <li><a href="{% url 'crm:console_list' %}">Consoles</a></li>
                <li><a href="{% url 'crm:videogame_list' %}">Video Games</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                                <div class="caption">
                                    <h2>Collectors</h2>
                                    <p>Here is the information of the Collectors. </p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'crm:collector_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/cupcakes.jpeg" %}" alt="cupcakes"/>
                                <div class="caption">
                                    <h2>Consoles</h2>
                                    <p>Here is the information of the Consoles.</p>
                                    <p><a class="btn btn-default" href="{% url 'crm:console_list' %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/lunch.jpeg" %}" alt="lunch"/>
                                <div class="caption">
                                    <h2>Video Games</h2>
                                    <p>Here is the information of the Video Games. </p>
                                    <p><a class="btn btn-default" href="{% url 'crm:videogame_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

crm/templates/crm/collector_delete.html
{% block body_block %}
    <h1>Delete {{ collector.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=collector.coll_number %} ">Cancel</a>

    </form>

{% endblock %}

crm/templates/crm/collector_edit.html
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Collector</h1>
    <form method="POST" class="collector-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

crm/templates/crm/collector_list.html
{% extends 'crm/base.html' %}
   {% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>GameCollection</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Welcome to the World of Games!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Collector Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Collector Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Account</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip Code</th>

                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for collector in collectors %}
                <tr>
                    <td>{{ collector.coll_name }}</td>
                    <td>{{ collector.email }}</td>
                    <td>{{ collector.phone_number }}</td>
                    <td>{{ collector.account_number }}</td>
                    <td>{{ collector.address }}</td>
                    <td>{{ collector.city }}</td>
                    <td>{{ collector.state }}</td>
                    <td>{{ collector.zipcode }}</td>
                    <td><a href="{% url 'crm:collector_edit' pk=collector.pk %}" class="btn btn-warning">Edit</a>

                    <td><a href="{% url 'crm:collector_delete' pk=collector.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                    <td><a href="{% url 'crm:summary' pk=collector.pk %}"
                           class="btn btn-primary">Summary</a>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}

crm/templates/crm/console_delete.html
{% block body_block %}
    <h1>Delete {{ console.console_name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=collector.coll_number %} ">Cancel</a>

    </form>

{% endblock %}

crm/templates/crm/console_edit.html
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Console</h1>
    <form method="POST" class="console-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

crm/templates/crm/console_list.html
{% extends 'crm/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>GameCollection</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Welcome to the World of Games!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Consoles Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Collector</th>
                <th>Console Name</th>
                <th>Description</th>
                <th>Console Model</th>
                <th>Console Color</th>
                <th>Console Brand</th>
                <th>Console Price</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for console in consoles %}
                <tr>
                    <td>{{ console.coll_name }}</td>
                    <td>{{ console.console_name }}</td>
                     <td>{{ console.description }}</td>
                    <td>{{ console.console_model }}</td>
                    <td>{{ console.console_color }}</td>
                    <td>{{ console.console_brand }}</td>
                    <td>{{ console.console_price }}</td>
                     <td><a href="{% url 'crm:console_edit' pk=console.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'crm:console_delete' pk=console.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <a href="{% url 'crm:console_new' %}" class="row"><span
                    class="btn btn-primary">Add Console</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

crm/templates/crm/console_new.html
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Console</h1>
    <form method="POST" class="service-form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

crm/templates/crm/home.html
{% extends 'crm/base.html' %}
{% load static %}
{% block content %}
   
   <body>
    <html>
            {% if user.is_authenticated %}
                <div class="page-container">

                    <h2 class="top-menu">Hello {{ user.username }},</h2>
                    <p>Please choose from below options.</p>

                </div>
            {% endif %}
            <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="links">
                            <!-- Example row of columns -->
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/customer.jpg" %}" alt="collector"/>
                                        <div class="caption">
                                            <h2>Collectors</h2>
                                            <p>Here is the information of the Collectors. </p>
                                            <p><a class="btn btn-primary" href="{% url 'crm:collector_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/cupcakes.jpeg" %}" alt="consoles"/>
                                        <div class="caption">
                                            <h2>Consoles</h2>
                                            <p>Here is the information of the Consoles.</p>
                                            <p><a class="btn btn-primary" href="{% url 'crm:console_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/lunch.jpeg" %}" alt="lunch"/>
                                        <div class="caption">
                                            <h2>Video Games</h2>
                                            <p>Here is the information of the Video Games.</p>
                                            <p><a class="btn btn-primary" href="{% url 'crm:videogame_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </body>
    </html>
{% endblock %}

crm/templates/crm/videogame_delete.html
{% block body_block %}
    <h1>Delete {{ videogame.videogame_name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'crm:home' pk=collector.coll_number %} ">Cancel</a>

    </form>

{% endblock %}

crm/templates/crm/videogame_edit.html
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Console</h1>
    <form method="POST" class="collector-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

crm/templates/crm/videogame_list.html
{% extends 'crm/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>GameCollection</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Welcome to the World of Games!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Video Games Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Collector</th>
                <th>Video Game Title</th>
                <th>Console</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Price</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for videogame in videogames %}
                <tr>
                    <td>{{ videogame.coll_name }}</td>
                    <td>{{ videogame.videogame_name }}</td>
                     <td>{{ videogame.videogame_console }}</td>
                    <td>{{ videogame.v_description }}</td>
                    <td>{{ videogame.quantity }}</td>
                    <td>{{ videogame.videogame_charge }}</td>
                     <td><a href="{% url 'crm:videogame_edit' pk=videogame.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'crm:videogame_delete' pk=videogame.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <a href="{% url 'crm:videogame_new' %}" class="row"><span
                    class="btn btn-primary">Add Video Game</span></a>
        </div>
    </div>
    </body>
    </html>
{% endblock %}

crm/templates/crm/videogame_new.html
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Video Game</h1>
    <form method="POST" class="service-form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}